# Entanglement Feature Learning

## EFL

### Convension of Coupling Constants
The original EFL model (for the Ising case) is
$$E[\sigma]=-\sum_{\langle ij\rangle}J_{ij} \chi(\sigma_i^{-1}\sigma_j),$$
where $J_{ij}=\ln D_{ij}$ and $\sigma_{i}$ takes values in the $S_2$ group, and the cycle trace $\chi$ maps $()\to2$, $(1,2)\to1$. The energy difference is one unit of $J_{ij}$. Note that each bond $\langle ij\rangle$ is added only once in the summation. Now for easier treatment in numerics, we map the $S_2$ spin $\sigma_i$ to a $\mathbb{Z}_2$ spin $s_i$, s.t. the energy model becomes
$$E[s]=-\frac{1}{2}\sum_{\langle ij\rangle}J_{ij}s_is_j=-\frac{1}{4}\sum_{i j}J_{ij}s_is_j.$$
We then define
$$K_{ij}=\frac{1}{2}J_{ij}=\frac{1}{2}\ln D_{ij},$$
and rewrite the energy model as
$$E[s]=-\frac{1}{2}\sum_{ij}K_{ij}s_is_j,$$
where the summation double counts a bond, and $s_{i}=\pm1$.

### Deep Boltzmann Machine (Model)

Layers: $s^{0},s^{1},\cdots$, where $s^0$ is the visible layer, rests are hidden layers. The energy model:
$$E[s]=-\sum_{l=1:L}\sum_{i j}s_i^{l-1}K_{ij}^l s_j^l.$$

## Restricted Boltzman Machine (RBM)

### RBM Kernel
Differences to standard RBM:
- the binary units takes values $\pm1$ instead of $0,1$.
- **unbiased**, RTN of pure state are not biased, so the only variational parameter is the weight matrix.
- elements in the weight matrixes are **positive** definite, because they correspnd to the logarithmic bond dimension.

Initialization of weight matrix. Wish to:
- reflect the locality.
- ferromagnetic, tune to critical.
- with some randomness.

Gibbs sampling:
- propagating up:
$$h_j\leftarrow\tanh \left\{\begin{array}{cc}\sum_{i}W_{ij}v_i & \text{default, top},\\ 2\sum_{i}W_{ij}v_i & \text{bottom, intermediate},\end{array}\right.$$
- propagating down:
$$v_i\leftarrow\tanh \left\{\begin{array}{cc}\sum_{j}W_{ij}h_j & \text{default, bottom},\\ 2\sum_{j}W_{ij}h_j & \text{top, intermediate},\end{array}\right.$$

Update rule ($\lambda_\text{l}$ learning rate, $\lambda_\text{f}$ forgetting rate):
$$W\leftarrow \text{relu}[(1-\lambda_\text{f})W+\lambda_\text{l} (v^{\intercal}(0) h(0)-v^{\intercal}(\infty) h(\infty))]$$
- If any element in $W$ becomes negative, the element is set to zero.
- Forgetting rate can be used to control the bond dimension.

In [288]:
%run 'EFL.py'
rbm = RBM(4,2)

In [287]:
print(rbm.learn(numpy.asarray(numpy.random.randint(0,2,(40,4))*2-1,dtype=float),0.1,0.01))
rbm.W.get_value()

0.7453134201113543


array([[ 0.165,  0.011],
       [ 0.708,  0.176],
       [ 0.120,  0.285],
       [ 0.071,  0.809]])

In [366]:
print(rbm.learn(numpy.array([[1,1,1,1],[-1,1,-1,1]]*10,dtype=float),0.1,0.01))
rbm.W.get_value()

1.081018265501512


array([[ 1.194,  0.031],
       [ 0.005,  0.940],
       [ 1.189,  0.003],
       [ 0.000,  0.946]])

#### Test by Ideal States
* trivial product state: deep PM, all Ising configuration equal weight.
* random state (maximally thermalized): deep FM, all up or all down.

In [16]:
%run EFL.py
train_FM = numpy.array([[1,1,1,1],[-1,-1,-1,-1]]*200,dtype=float)
train_AFM = numpy.array([[1,-1,1,-1],[-1,1,-1,1]]*200,dtype=float)
train_PM = numpy.asarray(numpy.random.randint(0,2,(400,4))*2-1,dtype=float)
#lr_table = [0.2,0.3,0.25,0.15,0.1]
#fr_table = [0.05,0.01,0.,0.,0.]
lr_table = [0.5,0.3,0.2,0.15,0.1,0.1,0.1]
fr_table = [0.,0.,0.,0.,0.,0.,0.]

FM, maximally thermal.

In [20]:
rbm = RBM(Nv=4,Nh=2)
for epoch in range(7):
    cost = rbm.learn(train_FM,lr_table[epoch],fr_table[epoch])
    print('Epoch %d: '%epoch, 'cost = %f'%cost)
rbm.W.get_value()

Epoch 0:  cost = 0.946498
Epoch 1:  cost = 0.901662
Epoch 2:  cost = 0.687882
Epoch 3:  cost = 0.599588
Epoch 4:  cost = 0.612765
Epoch 5:  cost = 0.556824
Epoch 6:  cost = 0.536112


array([[ 0.845,  0.575],
       [ 1.516,  0.517],
       [ 0.737,  0.613],
       [ 0.642,  0.933]])

PM, trivial product state.

In [31]:
rbm = RBM(Nv=4,Nh=2)
for epoch in range(7):
    cost = rbm.learn(train_PM,lr_table[epoch],fr_table[epoch])
    print('Epoch %d: '%epoch, 'cost = %f'%cost)
rbm.W.get_value()

Epoch 0:  cost = 1.026209
Epoch 1:  cost = 1.021890
Epoch 2:  cost = 1.005196
Epoch 3:  cost = 0.953806
Epoch 4:  cost = 0.973413
Epoch 5:  cost = 0.966338
Epoch 6:  cost = 0.966973


array([[ 1.397,  0.003],
       [ 0.089,  0.006],
       [ 0.000,  0.400],
       [ 0.018,  0.692]])

### Convolutional RBM
Assumption: translational symmetry (or in statistical sense under disorder average). Weights are shared among kernels for each layer and each group. This makes the algorithm scalable. For disordered system, this will learn the disorder averaged entanglement features.

Consider a 1D free fermion CFT, the Renyi entropy given by (acorrding to Calabrese and Cardy 2004, 2009)
$$S\propto\sum_{i,j}\ln|u_i-v_j|-\sum_{i<j}\ln|u_i-u_j|-\sum_{i<j}\ln|v_i-v_j|.$$
$u_i$ and $v_i$ are positions of kinks and antikinks in the Ising configuraiton.

In [26]:
from itertools import combinations
def entropy_CFT(kinks):
    us = kinks[0::2]
    vs = kinks[1::2]
    Suv = sum(numpy.log(abs(u-v)) for u in us for v in vs)
    Suu = sum(numpy.log(abs(u1-u2)) for u1, u2 in combinations(us,2))
    Svv = sum(numpy.log(abs(v1-v2)) for v1, v2 in combinations(vs,2))
    S = Suv-Suu-Svv
    return S
entropy_CFT([3,10])

1.9459101490553132

## Deep Boltzmann Machine

Create a DBM and prepare training set.

In [32]:
%run 'EFL.py'
dbm = DBM([8,4,2,1])
test_samples = [
    [+1,+1,+1,+1,+1,+1,+1,+1],
    [-1,-1,-1,-1,-1,-1,-1,-1],
    [+1,+1,+1,+1,-1,-1,-1,-1],
    [-1,-1,-1,-1,+1,+1,+1,+1],
    #[+1,+1,-1,-1,-1,-1,+1,+1],
    #[-1,-1,+1,+1,+1,+1,-1,-1]
]
data = Server(test_samples*100,15)
#data = Server(numpy.random.randint(0,2,(200,8))*2-1,10)

Pretrain and show weights.

In [33]:
dbm.pretrain(data,lrs=[0.5,0.3,0.2,0.15],frs=[0.05,0.01])

Pretraining layer 0:
    Epoch 0: cost = 0.575124
    Epoch 1: cost = 0.190124
    Epoch 2: cost = 0.065941
    Epoch 3: cost = 0.030259
    Epoch 4: cost = 0.055031
    Epoch 5: cost = 0.010158
    Epoch 6: cost = 0.006926
Pretraining layer 1:
    Epoch 0: cost = 1.623854
    Epoch 1: cost = 1.452538
    Epoch 2: cost = 1.115676
    Epoch 3: cost = 0.755499
    Epoch 4: cost = 0.741680
    Epoch 5: cost = 0.667127
    Epoch 6: cost = 0.500334
Pretraining layer 2:
    Epoch 0: cost = 1.017601
    Epoch 1: cost = 1.001798
    Epoch 2: cost = 1.004361
    Epoch 3: cost = 1.003599


In [34]:
for rbm in dbm.rbms:
    print(rbm.W.get_value())

[[ 1.356  1.367  0.000  0.000]
 [ 1.330  1.335  0.021  0.020]
 [ 1.306  1.299  0.067  0.067]
 [ 1.258  1.322  0.013  0.013]
 [ 0.017  0.018  1.357  1.333]
 [ 0.027  0.027  1.415  1.351]
 [ 0.097  0.098  1.432  1.428]
 [ 0.044  0.044  1.355  1.442]]
[[ 1.295  0.033]
 [ 1.290  0.047]
 [ 0.060  1.330]
 [ 0.033  1.318]]
[[ 0.025]
 [ 0.014]]


In [35]:
f = theano.function([dbm.input],dbm.rbms[1].output)
f([[+1,+1,+1,+1,+1,+1,+1,+1],
   [-1,-1,-1,-1,-1,-1,-1,-1],
   [-1,-1,-1,-1,+1,+1,+1,+1],
   [+1,+1,+1,+1,-1,-1,-1,-1]])

array([[ 1.000,  1.000],
       [-1.000, -1.000],
       [-1.000,  1.000],
       [ 1.000, -1.000]])

Fine-tuning and show weights.

In [36]:
dbm.finetune(data,10,lrs=[0.5,0.5,0.4,0.3,0.2,0.1])

    Epoch 0: cost = 0.005486
    Epoch 1: cost = 0.003521
    Epoch 2: cost = 0.003186
    Epoch 3: cost = 0.001988
    Epoch 4: cost = 0.001897
    Epoch 5: cost = 0.001822
    Epoch 6: cost = 0.001761
    Epoch 7: cost = 0.001747
    Epoch 8: cost = 0.001740
    Epoch 9: cost = 0.001734


In [37]:
for rbm in dbm.rbms:
    print(rbm.W.get_value())

[[ 1.712  1.722  0.000  0.000]
 [ 1.647  1.652  0.000  0.000]
 [ 1.766  1.759  0.000  0.000]
 [ 1.528  1.592  0.000  0.000]
 [ 0.000  0.000  1.680  1.656]
 [ 0.000  0.000  1.755  1.691]
 [ 0.000  0.000  1.731  1.727]
 [ 0.000  0.000  1.657  1.743]]
[[ 1.293  0.000]
 [ 1.288  0.000]
 [ 0.000  1.330]
 [ 0.000  1.318]]
[[ 0.018]
 [ 0.000]]


## Random Heisenberg Model

Random Heisenberg model:
$$H=J_1\sum_{\langle ij\rangle}\vec{S}_i\cdot\vec{S}_j+J_2\sum_{\langle\langle ij\rangle\rangle}(S_i^+S_j^-+h.c.)+\sum_i h_i S_i^z,$$
where $h_i\in[-W,W]$ is independently random on each site. According to Vedica, the MBL-ETH transition happens around $W_c\simeq 5$. We assume periodic boundary condition, and ED the Hamiltonian in the total-$S^z$ zero sector.

`Entanglement` object takes the many-body wave function given by `random_Heisenberg`. It than perform the MPS decomposition, and construct  entanglement entropy (2nd Renyi, in unit of bit) for all entanglement regions (secified by Ising configruation). The result is stored as a dict in `Entanglement.Sdict`.

In [255]:
%run 'EFL.py'
ent = Entanglement(random_Heisenberg(L = 10, W = 1.))
d = {k:[] for k in range(0,6)}
for config, S in ent.Sdict.items():
    d[min(config.count(1),config.count(-1))].append(S)
{k:(numpy.mean(Ss), numpy.std(Ss)/numpy.mean(Ss)) for k, Ss in d.items()}

{0: (-1.6017132519074577e-15, -0.1999999999999999),
 1: (0.98503959530704377, 0.016471315244866325),
 2: (1.9095470859390562, 0.029583699542407138),
 3: (2.7245355665404101, 0.034817811191220994),
 4: (3.3230399205273935, 0.040609214620450293),
 5: (3.5502721680280094, 0.04225125503175331)}