Import Tensorflow and open a session.

In [1]:
%run 'Ising.py'

### Determinant
Calculate matrix determinant

In [335]:
W = tf.constant([[0.,1.,1.,1.],
                 [-1.,0.,1.,-1.],
                 [-1.,-1.,0.,1.],
                 [-1.,1.,-1.,0.]])
f = tf.matrix_determinant(W)
sess.run(f)

9.0

Train by minimizing the ln(det(W)). TF knows how to do the gradient.

In [336]:
W = tf.Variable([[0.,1.,1.,1.],
                 [-1.,0.,1.,-1.],
                 [-1.,-1.,0.,1.],
                 [-1.,1.,-1.,0.]])
f = tf.log(tf.matrix_determinant(W))
init = tf.global_variables_initializer()
optimizer = tf.train.GradientDescentOptimizer(0.1)
train = optimizer.minimize(f)
sess.run(init)
for i in range(5):
    sess.run(train)
    print(sess.run(f))

2.06162
1.91632
1.75986
1.5904
1.4056


### Sparse Tensor
Sparse tensor must be converted to dense when passed to the determinant op.

In [337]:
W = tf.SparseTensor(indices=[[0, 0], [1, 1]], values=[1., 2.], dense_shape=[2, 2])
W_dense = tf.sparse_tensor_to_dense(W)
f = tf.log(tf.matrix_determinant(W_dense))
sess.run(f)

0.69314718

## Entanglement
### Entanglement Regions

In [289]:
list(Region({1,2},4).equivalences())

[{2, 3}, {0, 1}, {1, 2}, {0, 3}]

In [290]:
Region({1,2},4).config()

array([ 1, -1, -1,  1])

In [291]:
list(Regions(8).consecutives())

[set(),
 {0},
 {0, 1},
 {0, 1, 2},
 {0, 1, 2, 3},
 {0, 1, 2, 3, 4},
 {0, 1, 2, 3, 4, 5},
 {0, 1, 2, 3, 4, 5, 6},
 {0, 1, 2, 3, 4, 5, 6, 7}]

In [292]:
list(Regions(8).representatives())

[set(),
 {0},
 {0, 1},
 {0, 2},
 {0, 3},
 {0, 4},
 {0, 1, 2},
 {0, 1, 3},
 {0, 1, 4},
 {0, 2, 4},
 {0, 2, 5},
 {0, 1, 2, 3},
 {0, 1, 2, 4},
 {0, 1, 2, 5},
 {0, 1, 3, 5},
 {0, 1, 3, 6},
 {0, 1, 4, 5},
 {0, 2, 4, 6}]

### Entanglement Entropy
Entanglement entropy of free fermion.
$$H=\sum_{i}(1+(-)^i m)\mathrm{i}\chi_{i}\chi_{i+1}$$

In [406]:
FF = FreeFermion(mass=1.e-10, size=64, partitions=8)
[(region.config().astype(np.int),FF.S(region)) for region in FF.regions.representatives()]

[(array([1, 1, 1, 1, 1, 1, 1, 1]), 0.0),
 (array([-1,  1,  1,  1,  1,  1,  1,  1]), 0.95493682107909517),
 (array([-1, -1,  1,  1,  1,  1,  1,  1]), 1.0695809714486366),
 (array([-1,  1, -1,  1,  1,  1,  1,  1]), 1.8394650796478977),
 (array([-1,  1,  1, -1,  1,  1,  1,  1]), 1.8774657088562541),
 (array([-1,  1,  1,  1, -1,  1,  1,  1]), 1.8845279404467987),
 (array([-1, -1, -1,  1,  1,  1,  1,  1]), 1.1144620738852469),
 (array([-1, -1,  1, -1,  1,  1,  1,  1]), 1.9215689122523467),
 (array([-1, -1,  1,  1, -1,  1,  1,  1]), 1.9662565321942238),
 (array([-1,  1, -1,  1, -1,  1,  1,  1]), 2.699823845574632),
 (array([-1,  1, -1,  1,  1, -1,  1,  1]), 2.7309564498090433),
 (array([-1, -1, -1, -1,  1,  1,  1,  1]), 1.1271197777813784),
 (array([-1, -1, -1,  1, -1,  1,  1,  1]), 1.9409047304222073),
 (array([-1, -1, -1,  1,  1, -1,  1,  1]), 1.9788185519557893),
 (array([-1, -1,  1, -1,  1, -1,  1,  1]), 2.7501420605911471),
 (array([-1, -1,  1, -1,  1,  1, -1,  1]), 2.7429991569574717),

### Square Lattice Adjacency Matices

In [1]:
%run 'Ising.py'

In [2]:
mdl = SquareModel(Lx = 4, Lz =2)
writer = tf.summary.FileWriter('./log/test')
writer.add_graph(sess.graph)

In [13]:
init = tf.global_variables_initializer()
sess.run(init)
sess.run(mdl.cost, {mdl.confs:[[1,-1,1,-1]], mdl.S:[0.]})

10.645202427846879

In [379]:
np.eye(2)

array([[ 1.000,  0.000],
       [ 0.000,  1.000]])